/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as BoardImport } from "./routes/board";
import { Route as IndexImport } from "./routes/index";
import { Route as FilesSplatImport } from "./routes/files/$";

// Create/Update Routes

const BoardRoute = BoardImport.update({
  id: "/board",
  path: "/board",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const FilesSplatRoute = FilesSplatImport.update({
  id: "/files/$",
  path: "/files/$",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/board": {
      id: "/board";
      path: "/board";
      fullPath: "/board";
      preLoaderRoute: typeof BoardImport;
      parentRoute: typeof rootRoute;
    };
    "/files/$": {
      id: "/files/$";
      path: "/files/$";
      fullPath: "/files/$";
      preLoaderRoute: typeof FilesSplatImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/board": typeof BoardRoute;
  "/files/$": typeof FilesSplatRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/board": typeof BoardRoute;
  "/files/$": typeof FilesSplatRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/board": typeof BoardRoute;
  "/files/$": typeof FilesSplatRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/board" | "/files/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/board" | "/files/$";
  id: "__root__" | "/" | "/board" | "/files/$";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BoardRoute: typeof BoardRoute;
  FilesSplatRoute: typeof FilesSplatRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  FilesSplatRoute: FilesSplatRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/board",
        "/files/$"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/board": {
      "filePath": "board.tsx"
    },
    "/files/$": {
      "filePath": "files/$.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
